server:
  port: 8085
spring:
  cloud:
    inetutils:
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet8'
  thymeleaf:
    check-template-location: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.118.103:3306/tx_msg?useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=false&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    druid:
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 控制台管理用户名和密码
        login-username: admin
        login-password: admin
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: "classpath:mapper/*.xml"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
    logfile:
      external-file: /home/app/logs/tx-msg-dev.log

rocketmq:
  name-server: 192.168.118.104:9876
  producer:
    group: producer_pay
    send-message-timeout: 30000
    retry-times-when-send-failed: 3
    retry-times-when-send-async-failed: 2
    max-message-size: 4096
    compress-message-body-threshold: 4096
    retry-next-server: false

logging:
  file:
    name: /home/app/logs/tx-msg-dev.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){洋红色} %clr(- --){微弱} %clr([%15.15t]){微弱} %clr(%-40.40logger{39}){青色} %clr(:){微弱} %m%n%wEx"


xxl:
  job:
    admin-addresses: http://192.168.118.103:8989/xxl-job-admin
    access-token: default_token
    app-name: xxl-job-executor-msg
    ip: 192.168.118.1
    port: 8001
    log-path: /home/app/logs/xxl-job/msg
    log-retention-days: 30